from .game import player, LEFT, RIGHT, UP, DOWN

player.walk(LEFT)
player.walk(LEFT)
player.walk(LEFT)
player.walk(LEFT)
player.walk(LEFT)
player.walk(LEFT)
player.walk(LEFT)
player.walk(LEFT)
player.walk(LEFT)
player.walk(LEFT)
player.walk(LEFT)
player.walk(LEFT)
player.walk(LEFT)
player.walk(LEFT)
player.walk(LEFT)
player.walk(LEFT)
player.walk(LEFT)
player.walk(LEFT)
player.walk(LEFT)
player.walk(LEFT)
player.walk(LEFT)
player.walk(LEFT)
player.walk(LEFT)
player.walk(LEFT)
player.walk(LEFT)
player.walk(LEFT)
player.walk(LEFT)
player.walk(LEFT)
player.walk(LEFT)
player.walk(LEFT)
player.walk(LEFT)
player.walk(LEFT)
player.walk(LEFT)
player.walk(LEFT)
player.walk(LEFT)
player.walk(LEFT)
player.walk(LEFT)
player.walk(LEFT)
player.walk(LEFT)
player.walk(LEFT)
player.walk(LEFT)
player.walk(LEFT)
player.walk(LEFT)
player.walk(LEFT)
player.walk(LEFT)
player.walk(LEFT)
player.walk(LEFT)
player.walk(LEFT)
player.walk(LEFT)
player.walk(LEFT)
player.walk(LEFT)
player.walk(LEFT)
player.walk(LEFT)
player.print("?")
player.print("DIWALHDWA WAODWA WAIDHWA WIADHWA DWKA\nDHW HDWUKADWA BWDUAIDHWA DBWUADWAK WHDUWADH DWUAKD")
player.print("DIWALHDWA WAODWA WAIDHWA WIADHWA DWKA\nDHW HDWUKADWA BWDUAIDHWA DBWUADWAK WHDUWADH DWUAKD")
player.print("DIWALHDWA WAODWA WAIDHWA WIADHWA DWKA\nDHW HDWUKADWA BWDUAIDHWA DBWUADWAK WHDUWADH DWUAKD")
player.print("DIWALHDWA WAODWA WAIDHWA WIADHWA DWKA\nDHW HDWUKADWA BWDUAIDHWA DBWUADWAK WHDUWADH DWUAKD")
player.print("DIWALHDWA WAODWA WAIDHWA WIADHWA DWKA\nDHW HDWUKADWA BWDUAIDHWA DBWUADWAK WHDUWADH DWUAKD")
player.print("DIWALHDWA WAODWA WAIDHWA WIADHWA DWKA\nDHW HDWUKADWA BWDUAIDHWA DBWUADWAK WHDUWADH DWUAKD")
player.print("DIWALHDWA WAODWA WAIDHWA WIADHWA DWKA\nDHW HDWUKADWA BWDUAIDHWA DBWUADWAK WHDUWADH DWUAKD")
player.print("DIWALHDWA WAODWA WAIDHWA WIADHWA DWKA\nDHW HDWUKADWA BWDUAIDHWA DBWUADWAK WHDUWADH DWUAKD")
player.print("!!!")
player.print("!!!")
player.print("??????")
player.print("gn")
player.print(":)")
player.print(":)")